on: push
name: Validate commit message
jobs:
  build:
    name: Validate commit message
    runs-on: ubuntu-latest
    steps:
      - name: Validate
        uses: harmenjanssen/commit-message-validation-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
